"""Generate web/src/api/schema.gen.ts from the FastAPI OpenAPI schema.

Rule 0.5: the Pydantic models are the only definition of these shapes. This script is how the
frontend gets them. `--check` regenerates into a temp file and fails if it differs from what is
committed, so a backend model change that was not propagated breaks `make check` rather than
production.
"""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "web" / "src" / "api" / "schema.gen.ts"
HEADER = "// GENERATED by scripts/gen_types.py from the OpenAPI schema. Do not edit by hand.\n"


def openapi_json() -> str:
    sys.path.insert(0, str(ROOT))
    from server.main import create_app

    return json.dumps(create_app().openapi(), indent=2, sort_keys=True)


def generate() -> str:
    with tempfile.TemporaryDirectory() as tmp:
        spec = Path(tmp) / "openapi.json"
        spec.write_text(openapi_json())
        result = subprocess.run(
            ["npx", "--yes", "openapi-typescript", str(spec)],
            cwd=ROOT / "web",
            capture_output=True,
            text=True,
        )
    if result.returncode != 0:
        raise SystemExit(f"openapi-typescript failed:\n{result.stderr}")
    return HEADER + result.stdout


def main() -> int:
    generated = generate()
    if "--check" in sys.argv:
        current = TARGET.read_text() if TARGET.exists() else ""
        if current != generated:
            print(
                "schema.gen.ts is out of date with the Pydantic models.\n"
                "Run `make types` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print("schema.gen.ts is up to date")
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(generated)
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
